
*****
X-Ray
*****
    - AWS X-Ray makes it easy for developers to analyze the behavior of their production, distributed applications 
      with end-to-end tracing capabilities
    - You can use X-Ray to identify performance bottlenecks, edge case errors, and other hard to detect issues
    ******
    Traces
    ******
        - A trace ID tracks the path of a request through your application
        - A trace collects all the segments generated by a single request
        - That request is typically an HTTP GET or POST request that travels through a load balancer, hits your 
          application code, and generates downstream calls to other AWS services or external web APIs
        - The first supported service that the HTTP request interacts with adds a trace ID header to the request, 
          and propagates it downstream to track the latency, disposition, and other request data
    ********
    Segments
    ********
        - The compute resources running your application logic send data about their work as segments
        - A segment provides the resources name, details about the request, and details about the work done
          For example, when an HTTP request reaches your application, it can record the following data about
            The host- hostname, alias or IP address
            The request- method, client address, path, user agent
            The response- status, content
            The work done- start and end times, subsegments
            Issues that occur- errors, faults and exceptions, including automatic capture of exception stacks
    ***********
    Subsegments
    ***********
        - A segment can break down the data about the work done into subsegments
        - Subsegments provide more granular timing information and details about downstream calls 
    ********
    Sampling
    ********
        - By default, the x-ray SDK records the first request each second and 5% of any additional requests
        - Sampling helps reduce X-Ray logging thus helps save money
        - To ensure efficient tracing and provide a representative sample of the requests that your application 
          serves, the X-Ray SDK applies a sampling algorithm to determine which requests get traced
    ***********
    Annotations
    ***********
        - When you instrument your application, the X-Ray SDK records information about incoming and outgoing 
          requests, the AWS resources used, and the application itself
        - You can add other information to the segment document as annotations and metadata
        - Use annotations to record data that you want to use to group traces in the console, or when calling 
          the GetTraceSummaries API
        - X-Ray indexes up to 50 annotations per trace
    ********
    Metadata
    ********
        - Metadata are key-value pairs with values of any type 
        - Use metadata to record data you want to store in the trace but dont need to use for searching Traces
    **************
    x-ray security
    **************
        - IAM for authorization
        - KMS for encryption at rest
    ************
    X-Ray daemon
    ************
        - The AWS X-Ray daemon is a software application that listens for traffic on UDP port 2000, gathers raw 
          segment data, and relays it to the AWS X-Ray API
        - The daemon works in conjunction with the AWS X-Ray SDKs and must be running so that data sent by the 
          SDKs can reach the X-Ray service
        - Lambda runs the daemon automatically any time a function is invoked for a sampled request
        - On Elastic Beanstalk, use the XRayEnabled configuration option to run the daemon on the instances in 
          your environment
        - To run the X-Ray daemon locally, on-premises, or on other AWS services, download it, run it, and then 
          give it permission to upload segment documents to X-Ray
        - Traces are sent to x-ray using the daemon to avoid throttling, the daemon sends traces in batches
        - Elastic Beanstalk does not provide the X-Ray daemon on the Multi-container docker
        - You can use the console to turn on X-Ray integration
        - You can configure it in your application source code with a configuration file
            Use the .ebextension file
            Example .ebextensions/xray-daemon.config
                        option_settings:
                        aws:elasticbeanstalk:xray:
                            XRayEnabled: true
    *************************
    ECS and X-Ray Integration
    *************************
        ***********
        ECS Cluster
        ***********
            - We can install the daemon in each EC2 Instance as a single X-Ray Daemon container
            - We can install on each container app running on the EC2 instance as an X-Ray Sidecar
        ***************
        Fargate Cluster
        ***************
            - This uses the X-Ray SideCar method
